xpathmap = {
    "btn_tambah_kerusakan_kerugian": '//*[@id="content-container"]/div[3]/div[2]/div[2]/div/div/div[1]/button',
    "kerusakan_kerugian_kecamatan": "/html/body/div[2]/div[2]/div/div/div/div/div[1]/div/div/div/div/input",
    "kerusakan_kerugian_ds_kelurahan": "/html/body/div[2]/div[2]/div/div/div/div/div[2]/div/div/div/div/input",
    "kerusakan_kerugian_tgl_waktu": "/html/body/div[2]/div[2]/div/div/div/div/div[3]/div/div/div/input",
    "kategori": {
        "rumah": {
            "rusak_rumah_rusak_ringan": "/html/body/div[2]/div[2]/div/div/div/form/div[1]/div/div[1]/div/div/div[1]/input",
            "rusak_rumah_rusak_sedang": "/html/body/div[2]/div[2]/div/div/div/form/div[1]/div/div[2]/div/div/div[1]/input",
            "rusak_rumah_rusak_berat": "/html/body/div[2]/div[2]/div/div/div/form/div[1]/div/div[3]/div/div/div[1]/input",
            "rusak_rumah_rusak_terendam": "/html/body/div[2]/div[2]/div/div/div/form/div[1]/div/div[4]/div/div/div[1]/input",
            "rugi_rumah": "/html/body/div[2]/div[2]/div/div/div/form/div[1]/div/div[6]/div/div/div[1]/input",
        },
        "rumah_ibadah": {
            "rusak_ibadah_rusak_ringan": "/html/body/div[2]/div[2]/div/div/div/form/div[2]/div/div[1]/div/div/div[1]/input",
            "rusak_ibadah_rusak_sedang": "/html/body/div[2]/div[2]/div/div/div/form/div[2]/div/div[2]/div/div/div[1]/input",
            "rusak_ibadah_rusak_berat": "/html/body/div[2]/div[2]/div/div/div/form/div[2]/div/div[3]/div/div/div[1]/input",
            "rusak_ibadah_rusak_terendam": "/html/body/div[2]/div[2]/div/div/div/form/div[2]/div/div[4]/div/div/div[1]/input",
            "rugi_ibadah": "/html/body/div[2]/div[2]/div/div/div/form/div[2]/div/div[6]/div/div/div[1]/input",
        },
        "fasilitas_pendidikan": {
            "rusak_pendidikan_rusak_ringan": "/html/body/div[2]/div[2]/div/div/div/form/div[3]/div/div[1]/div/div/div[1]/input",
            "rusak_pendidikan_rusak_sedang": "/html/body/div[2]/div[2]/div/div/div/form/div[3]/div/div[2]/div/div/div[1]/input",
            "rusak_pendidikan_rusak_berat": "/html/body/div[2]/div[2]/div/div/div/form/div[3]/div/div[3]/div/div/div[1]/input",
            "rusak_pendidikan_rusak_terendam": "/html/body/div[2]/div[2]/div/div/div/form/div[3]/div/div[4]/div/div/div[1]/input",
            "rugi_pendidikan": "/html/body/div[2]/div[2]/div/div/div/form/div[3]/div/div[6]/div/div/div[1]/input",
        },
        "fasilitas_umum": {
            "rusak_umum_rusak_ringan": "/html/body/div[2]/div[2]/div/div/div/form/div[5]/div/div[1]/div/div/div[1]/input",
            "rusak_umum_rusak_sedang": "/html/body/div[2]/div[2]/div/div/div/form/div[5]/div/div[2]/div/div/div[1]/input",
            "rusak_umum_rusak_berat": "/html/body/div[2]/div[2]/div/div/div/form/div[5]/div/div[3]/div/div/div[1]/input",
            "rusak_umum_rusak_terendam": "/html/body/div[2]/div[2]/div/div/div/form/div[5]/div/div[4]/div/div/div[1]/input",
            "rugi_umum": "/html/body/div[2]/div[2]/div/div/div/form/div[5]/div/div[6]/div/div/div[1]/input",
        },
        "jalan_km": {
            "rusak_jalan_rusak_ringan": "/html/body/div[2]/div[2]/div/div/div/form/div[9]/div/div[1]/div/div/div[1]/input",
            "rusak_jalan_rusak_sedang": "/html/body/div[2]/div[2]/div/div/div/form/div[9]/div/div[2]/div/div/div[1]/input",
            "rusak_jalan_rusak_berat": "/html/body/div[2]/div[2]/div/div/div/form/div[9]/div/div[3]/div/div/div[1]/input",
            "rusak_jalan_rusak_terendam": "/html/body/div[2]/div[2]/div/div/div/form/div[9]/div/div[4]/div/div/div[1]/input",
            "rugi_jalan": "/html/body/div[2]/div[2]/div/div/div/form/div[9]/div/div[1]/div/div/div[6]/input",
        },
        "jembatan": {
            "rusak_jembatan_rusak_ringan": "/html/body/div[2]/div[2]/div/div/div/form/div[10]/div/div[1]/div/div/div[1]/input",
            "rusak_jembatan_rusak_sedang": "/html/body/div[2]/div[2]/div/div/div/form/div[10]/div/div[2]/div/div/div[1]/input",
            "rusak_jembatan_rusak_berat": "/html/body/div[2]/div[2]/div/div/div/form/div[10]/div/div[3]/div/div/div[1]/input",
            "rusak_jembatan_rusak_terendam": "/html/body/div[2]/div[2]/div/div/div/form/div[10]/div/div[4]/div/div/div[1]/input",
            "rugi_jembatan": "/html/body/div[2]/div[2]/div/div/div/form/div[10]/div/div[6]/div/div/div[1]/input",
        },
        "lahan_persawahan_ha": {
            "rusak_sawah_rusak_ringan": "/html/body/div[2]/div[2]/div/div/div/form/div[13]/div/div[1]/div/div/div[1]/input",
            "rusak_sawah_rusak_sedang": "/html/body/div[2]/div[2]/div/div/div/form/div[13]/div/div[2]/div/div/div[1]/input",
            "rusak_sawah_rusak_berat": "/html/body/div[2]/div[2]/div/div/div/form/div[13]/div/div[3]/div/div/div[1]/input",
            "rusak_sawah_rusak_terendam": "/html/body/div[2]/div[2]/div/div/div/form/div[13]/div/div[4]/div/div/div[1]/input",
            "rugi_sawah": "/html/body/div[2]/div[2]/div/div/div/form/div[13]/div/div[6]/div/div/div[1]/input",
        },
        "lahan_perkebunan_ha": {
            "rusak_kebun_rusak_ringan": "/html/body/div[2]/div[2]/div/div/div/form/div[14]/div/div[1]/div/div/div[1]/input",
            "rusak_kebun_rusak_sedang": "/html/body/div[2]/div[2]/div/div/div/form/div[14]/div/div[2]/div/div/div[1]/input",
            "rusak_kebun_rusak_berat": "/html/body/div[2]/div[2]/div/div/div/form/div[14]/div/div[3]/div/div/div[1]/input",
            "rusak_kebun_rusak_terendam": "/html/body/div[2]/div[2]/div/div/div/form/div[14]/div/div[4]/div/div/div[1]/input",
            "rugi_kebun": "/html/body/div[2]/div[2]/div/div/div/form/div[14]/div/div[6]/div/div/div[1]/input",
        },
        "hewan_ternak": {
            "total_hewan": "/html/body/div[2]/div[2]/div/div/div/form/div[15]/div/div[1]/div/div/div[1]/input",
            "rugi_hewan": "/html/body/div[2]/div[2]/div/div/div/form/div[15]/div/div[2]/div/div/div[1]/input",
        },
    },
    "kerugian_total": "/html/body/div[2]/div[2]/div/div/div/form/div[17]/div/div/div/div/div[1]/input",
    "btn_simpan_dampak_terkini": "/html/body/div[2]/div[2]/div/div/div/form/button",
}
