data_krs_krg = [
    {
        "kerusakan_kerugian_kecamatan": "Sragen",
        "kerusakan_kerugian_ds_kelurahan": "Sragen Tengah",
        "kerusakan_kerugian_tgl_waktu": "2026-01-08 17:15:00",
        "kategori": {
            "rumah": {
                "rusak_rumah_rusak_ringan": "3",
                "rusak_rumah_rusak_sedang": "",
                "rusak_rumah_rusak_berat": "",
                "rusak_rumah_rusak_terendam": "",
                "rugi_rumah": "",
            },
            "rumah_ibadah": {
                "rusak_ibadah_rusak_ringan": "3",
                "rusak_ibadah_rusak_sedang": "",
                "rusak_ibadah_rusak_berat": "",
                "rusak_ibadah_rusak_terendam": "",
                "rugi_ibadah": "",
            },
            "fasilitas_pendidikan": {
                "rusak_pendidikan_rusak_ringan": "",
                "rusak_pendidikan_rusak_sedang": "",
                "rusak_pendidikan_rusak_berat": "",
                "rusak_pendidikan_rusak_terendam": "",
                "rugi_pendidikan": "",
            },
            "fasilitas_umum": {
                "rusak_umum_rusak_ringan": "",
                "rusak_umum_rusak_sedang": "",
                "rusak_umum_rusak_berat": "",
                "rusak_umum_rusak_terendam": "",
                "rugi_umum": "",
            },
            "jalan_km": {
                "rusak_jalan_rusak_ringan": "",
                "rusak_jalan_rusak_sedang": "",
                "rusak_jalan_rusak_berat": "",
                "rusak_jalan_rusak_terendam": "",
                "rugi_jalan": "",
            },
            "jembatan": {
                "rusak_jembatan_rusak_ringan": "",
                "rusak_jembatan_rusak_sedang": "",
                "rusak_jembatan_rusak_berat": "",
                "rusak_jembatan_rusak_terendam": "",
                "rugi_jembatan": "",
            },
            "lahan_persawahan_ha": {
                "rusak_sawah_rusak_ringan": "",
                "rusak_sawah_rusak_sedang": "",
                "rusak_sawah_rusak_berat": "",
                "rusak_sawah_rusak_terendam": "",
                "rugi_sawah": "",
            },
            "lahan_perkebunan_ha": {
                "rusak_kebun_rusak_ringan": "",
                "rusak_kebun_rusak_sedang": "",
                "rusak_kebun_rusak_berat": "",
                "rusak_kebun_rusak_terendam": "",
                "rugi_kebun": "",
            },
            "hewan_ternak": {"total_hewan": "", "rugi_hewan": ""},
        },
        "kerugian_total": "1200000",
    },
    {
        "kerusakan_kerugian_kecamatan": "Karangmalang",
        "kerusakan_kerugian_ds_kelurahan": "Puro",
        "kerusakan_kerugian_tgl_waktu": "2026-01-08 17:15:00",
        "kategori": {
            "rumah": {
                "rusak_rumah_rusak_ringan": "2",
                "rusak_rumah_rusak_sedang": "",
                "rusak_rumah_rusak_berat": "",
                "rusak_rumah_rusak_terendam": "",
                "rugi_rumah": "",
            },
            "rumah_ibadah": {
                "rusak_ibadah_rusak_ringan": "",
                "rusak_ibadah_rusak_sedang": "",
                "rusak_ibadah_rusak_berat": "2",
                "rusak_ibadah_rusak_terendam": "",
                "rugi_ibadah": "",
            },
            "fasilitas_pendidikan": {
                "rusak_pendidikan_rusak_ringan": "",
                "rusak_pendidikan_rusak_sedang": "",
                "rusak_pendidikan_rusak_berat": "",
                "rusak_pendidikan_rusak_terendam": "",
                "rugi_pendidikan": "",
            },
            "fasilitas_umum": {
                "rusak_umum_rusak_ringan": "",
                "rusak_umum_rusak_sedang": "",
                "rusak_umum_rusak_berat": "",
                "rusak_umum_rusak_terendam": "",
                "rugi_umum": "",
            },
            "jalan_km": {
                "rusak_jalan_rusak_ringan": "",
                "rusak_jalan_rusak_sedang": "",
                "rusak_jalan_rusak_berat": "",
                "rusak_jalan_rusak_terendam": "",
                "rugi_jalan": "",
            },
            "jembatan": {
                "rusak_jembatan_rusak_ringan": "",
                "rusak_jembatan_rusak_sedang": "",
                "rusak_jembatan_rusak_berat": "",
                "rusak_jembatan_rusak_terendam": "",
                "rugi_jembatan": "",
            },
            "lahan_persawahan_ha": {
                "rusak_sawah_rusak_ringan": "",
                "rusak_sawah_rusak_sedang": "",
                "rusak_sawah_rusak_berat": "",
                "rusak_sawah_rusak_terendam": "",
                "rugi_sawah": "",
            },
            "lahan_perkebunan_ha": {
                "rusak_kebun_rusak_ringan": "",
                "rusak_kebun_rusak_sedang": "",
                "rusak_kebun_rusak_berat": "",
                "rusak_kebun_rusak_terendam": "",
                "rugi_kebun": "",
            },
            "hewan_ternak": {"total_hewan": "", "rugi_hewan": ""},
        },
        "kerugian_total": "1000000",
    },
    {
        "kerusakan_kerugian_kecamatan": "Karangmalang",
        "kerusakan_kerugian_ds_kelurahan": "Saradan",
        "kerusakan_kerugian_tgl_waktu": "2026-01-08 17:15:00",
        "kategori": {
            "rumah": {
                "rusak_rumah_rusak_ringan": "",
                "rusak_rumah_rusak_sedang": "2",
                "rusak_rumah_rusak_berat": "",
                "rusak_rumah_rusak_terendam": "",
                "rugi_rumah": "",
            },
            "rumah_ibadah": {
                "rusak_ibadah_rusak_ringan": "",
                "rusak_ibadah_rusak_sedang": "",
                "rusak_ibadah_rusak_berat": "",
                "rusak_ibadah_rusak_terendam": "",
                "rugi_ibadah": "",
            },
            "fasilitas_pendidikan": {
                "rusak_pendidikan_rusak_ringan": "",
                "rusak_pendidikan_rusak_sedang": "2",
                "rusak_pendidikan_rusak_berat": "",
                "rusak_pendidikan_rusak_terendam": "",
                "rugi_pendidikan": "",
            },
            "fasilitas_umum": {
                "rusak_umum_rusak_ringan": "",
                "rusak_umum_rusak_sedang": "",
                "rusak_umum_rusak_berat": "",
                "rusak_umum_rusak_terendam": "",
                "rugi_umum": "",
            },
            "jalan_km": {
                "rusak_jalan_rusak_ringan": "",
                "rusak_jalan_rusak_sedang": "",
                "rusak_jalan_rusak_berat": "",
                "rusak_jalan_rusak_terendam": "",
                "rugi_jalan": "",
            },
            "jembatan": {
                "rusak_jembatan_rusak_ringan": "",
                "rusak_jembatan_rusak_sedang": "",
                "rusak_jembatan_rusak_berat": "",
                "rusak_jembatan_rusak_terendam": "",
                "rugi_jembatan": "",
            },
            "lahan_persawahan_ha": {
                "rusak_sawah_rusak_ringan": "",
                "rusak_sawah_rusak_sedang": "",
                "rusak_sawah_rusak_berat": "",
                "rusak_sawah_rusak_terendam": "",
                "rugi_sawah": "",
            },
            "lahan_perkebunan_ha": {
                "rusak_kebun_rusak_ringan": "",
                "rusak_kebun_rusak_sedang": "",
                "rusak_kebun_rusak_berat": "",
                "rusak_kebun_rusak_terendam": "",
                "rugi_kebun": "",
            },
            "hewan_ternak": {"total_hewan": "", "rugi_hewan": ""},
        },
        "kerugian_total": "131242234",
    },
]
